id: P000365
initial_creation_type: ocr
created_at: 16/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN8015
  title: དཀར་ཁུང་།
  author: ''
  volumes:
    559ecf1df1f64484b717eb075ac5f8b5:
      image_group_id: I3CN8017
      title: Volume 1 of dkar khung /
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
