id: P000365
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8015
  title: དཀར་ཁུང་།
  author: ''
  volumes:
    559ecf1df1f64484b717eb075ac5f8b5:
      image_group_id: I3CN8017
      title: Volume 1 of dkar khung /
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
ebook_metadata:
  title: དཀར་ཁུང་།
  author: ''
  sku: P000365
  cover: cover.jpg
  layers:
  - pagination
